septober_v8/config/routes.rb
Rails.application.routes.draw do
  root "todos#index"

  get "login", to: "sessions#new", as: :login
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy", as: :logout
  get "signup", to: "users#new", as: :signup

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :show]

  resources :projects do
    member do
      get :procrastinate
    end
    resources :todos
  end

  resources :todos do
    member do
      get :sleep
      get :done
      get :undone
      get :toggle
      get :procrastinate
      get :set_priority
      get :set_bookmark
      get :set_todo_where
    end
  end

  # Health checks
  get "healthz", to: "pages#healthz"
  get "statusz", to: "pages#statusz"
  get "varz", to: "pages#varz"
end

septober_v8/app/models/todo.rb
class Todo < ApplicationRecord
  include ActsAsCarlesso
  
  belongs_to :user
  belongs_to :project
  belongs_to :todo, class_name: "Todo", foreign_key: :depends_on_id, optional: true

  acts_as_carlesso
  searchable_by :name, :description

  scope :recent, -> { where('created_at > ?', 1.week.ago) }
  scope :super_recent, -> { where('created_at > ?', 1.day.ago) }
  scope :overdue, -> { where('due < ?', Time.now) }
  scope :active, -> { where(active: true) }
  scope :done, -> { where(active: false) }
  scope :relevant, -> { where(priority: 1..3) }
  scope :owned_by, ->(user) { where(user_id: user.id) }

  validates :name, uniqueness: { scope: :user_id, message: "for this user is already created! (Cant have duplicate Todos)" }
  validates :project, :user, :name, presence: true
  attribute :priority, default: 3
  validates :priority, inclusion: { in: 1..5 }
  validates :progress_status, inclusion: { in: 0..100, message: "is a percentage, please go back to school :P" }, allow_nil: true

  before_create :apply_todo_regex_magic

  acts_as_taggable_on :tags
  acts_as_taggable_on :system_tags

  def to_s
    name.capitalize
  end

  def to_html
    "<span class='todo'>#{self.to_s}</span>"
  end

  def done?
    !active
  end

  def photo_url?
    photo_url.present?
  end

  def self.ids
    all.map(&:id)
  end

  def self.names
    all.map(&:name)
  end

  def progress_status?
    progress_status && progress_status > 0
  end

  def overdue?
    due < Date.today rescue false
  end

  def close_due?
    due < Date.today + 2 rescue false
  end

  def due_explaination
    return 'overdue' if overdue?
    return 'close' if close_due?
    'far'
  rescue
    "DueXplnErr"
  end

  def where?
    self.where.present?
  end

  def still_hidden?
    hide_until && hide_until > Time.now
  end

  def url?
    url.to_s.length > 4
  end

  def self.extract_tags_and_depure(str)
    begin
      words = str.split(/ /)
      tags = words.select{|w| w.match /^@/ }.map{|tag| tag.gsub(/^@/,'')}
      depured_str = words.select{|w| ! w.match /^@/ }.join(' ')
      return [depured_str,tags]
    rescue Exception => e
      puts "\n\tException!! #{e}"
      return [str, [] ]
    end
  end

  def apply_todo_regex_magic
    logger.info "Todo.apply_todo_regex_magic() for ticket ##{self.id rescue :NO_ID}"
    log = []
    begin
      log << "\tDEBUG: apply_todo_regex_magic START for: #{self.inspect}"
      str = self.name || ''
      self.due = Date.today if str.match( / today| oggi/i )
      self.due = Date.tomorrow if str.match( /tomorrow|domani/i )
      self.due = Date.yesterday if str.match( /yesterday| ieri/i )
      self.due ||= Date.today + 7 unless attribute_present?('due')
      
      self.priority = 1 if str.match /^\-\-|\.\.\.$/
      self.priority = 2 if str.match /^\-|\.\.$/
      self.priority = 4 if str.match /^\+|!$/
      self.priority = 5 if str.match /^\+\+|!!$/
      self.description = I18n.t(:quick_created) unless attribute_present?('description')

      if str.match(/ (http(s)?:\/\/\S+)($|\s)/)
        self.url = $1
        log << "URL correctly parsed: '#{$1}'"
        self.name = self.name.gsub($1,' (URL) ')
      end

      depured_str, mytags = Todo.extract_tags_and_depure(str)
      str = depured_str
      mytags.each{|tag|
        self.tag_list.add(tag.to_s)
      }
      self.name = depured_str

      unless attribute_present?('project_id')
        personal = Project.find_by(name: 'personal', user_id: self.user_id)
        if personal
            log << "PersProject: #{personal.inspect}"
            self.project_id = personal.id
        end
      end
      
      self.sys_notes = (self.sys_notes || '') + "\n\n---- LOGS: ----\n#{log.join("\n")}"
      return true
    rescue Exception => e
      logger.error "Todo.apply_todo_regex_magic Exception: #{ e.backtrace.join("\n") }"
      return false
    end
  end

  def self.provision_for_user(user)
    ver = '1.0.3'
    personal = Project.find_by(name: 'personal', user_id: user.id)
    work     = Project.find_by(name: 'work',     user_id: user.id)
    septober = Project.find_by(name: 'septober', user_id: user.id)
    tail = "--\nAutoProvisioned Todos v.#{ver}"
    
    return unless personal && work && septober

    create!([
      {user_id: user.id, project_id: personal.id, name: 'Go shopping' , 
        due: Date.today + 14 ,
        where: "Tesco, Parnell St, Dublin",
        description: "Buy Milk, Coffee, Toilet Paper, tomato, shrimps, peas, cream \n #{tail}" },
      {user_id: user.id, project_id: work.id,     name: 'Organize meeting to your boss by tomorrow!' , 
        priority: 4, 
        due: Date.tomorrow ,
        description: tail  },
      {user_id: user.id, project_id: septober.id,
         name: 'Cleanup the room' , 
         due: Date.today + 365 ,
         hide_until: Time.now + 86400 * 7 ,
         description: "Something to be done in 1yr time, hidden again for the next year!"+tail },
      {user_id: user.id, project_id: personal.id,
         name: 'Buy new shoes by saturday!' , 
         due: Date.today + 30 ,
         where: 'Grafton St, Dublin, Ireland',
         description: "Something to be done in 1yr time"+tail },
      {user_id: user.id, project_id: septober.id,
         name: 'Drink guinness with friends' , 
         photo_url: 'http://adsoftheworld.com/files/images/guinness-april-fool.preview.jpg',
         due: Date.today + 30 ,
         where: 'The Duke, Dublin, Ireland',
         description: "Something to be done in 1yr time"+tail },
      {user_id: user.id, project_id: septober.id, 
        due: Date.yesterday ,
        name: 'Thank Riccardo for this wonderful application' , description: "His email is #{$APP[:author] rescue "Dunno"}" },
    ])
  end
end

septober_v8/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :login_required, unless: -> { request.format.json? }

  def index
    user_id = current_user&.id || User.first&.id # Fallback for CLI testing without auth
    filter_conditions = { user_id: user_id }
    if params[:add_project]
      project = Project.find_by(name: params[:add_project], user_id: current_user.id)
      filter_conditions[:project_id] = project.id if project
    else
      # TODO: Implement home_visible logic properly if needed
    end

    @todos = Todo.where(filter_conditions)
                 .search(params[:q])
                 .joins(:project)
                 .order(active: :desc, priority: :desc, updated_at: :desc)
                 .limit(20)

    respond_to do |format|
      format.html
      format.json { render json: @todos }
      format.xml  { render xml: @todos }
    end
  end

  def show
    @todo = Todo.find_by(id: params[:id], user_id: current_user.id)
    respond_to do |format|
      format.html
      format.json { render json: @todo }
      format.xml  { render xml: @todo }
    end
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    if @todo.save
      flash[:notice] = "Successfully created todo ##{@todo.id} '#{@todo.to_s}'"
      redirect_to todos_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @todo = Todo.find_by(id: params[:id], user_id: current_user.id)
    if turbo_frame_request?
      render partial: "inline_form", locals: { todo: @todo }
    else
      render :edit
    end
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      if turbo_frame_request?
        render partial: "todo", locals: { todo: @todo }
      else
        flash[:notice] = "Successfully updated todo ##{@todo.id}"
        redirect_to todos_url
      end
    else
      if turbo_frame_request?
        render partial: "inline_form", locals: { todo: @todo }, status: :unprocessable_entity
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    flash[:notice] = "Successfully destroyed todo ##{@todo.id}."
    redirect_to todos_url
  end

  def toggle
    _update_active(:toggled)
  end

  def done
    _update_active(:deactivated, false)
  end

  def undone
    _update_active(:reactivated, true)
  end

  def set_priority
    _update_field(:priority, params[:new_priority])
  end

  def procrastinate
    n_days = params.fetch(:procrastinate_days, 7).to_i
    _update_field(:due, Date.today + n_days)
  end

  def sleep
    n_days = params.fetch(:hide_until_days, 8).to_i
    _update_field(:hide_until, Time.now + n_days.days)
  end

  private

  def _update_active(participle, new_active = nil)
    @todo = Todo.find_by(id: params[:id], user_id: current_user.id)
    new_active = !@todo.active if new_active.nil?
    
    if @todo.update(active: new_active)
      flash[:notice] = "Successfully '#{participle}' todo ##{params[:id]}"
      redirect_to todos_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def _update_field(field_name, new_val)
    @todo = Todo.find_by(id: params[:id], user_id: current_user.id)
    if @todo.update(field_name => new_val)
      flash[:notice] = "Successfully set '#{field_name}'='#{new_val}' for Todo ##{params[:id]}"
      redirect_to todos_url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def todo_params
    params.require(:todo).permit(:name, :description, :active, :due, :priority, :project_id, :url, :progress_status, :favorite, :hide_until, :depends_on_id, :source, :photo_url, :tag_list)
  end
end

septober_v8/app/helpers/todos_helper.rb
module TodosHelper
  #  Priorities  1        2      3       4        5
  PRIORITIES_NAMES = %w{ ZERO very_low low    normal  high     very_high }
  PRIORITIES_COLORS= %w{ ZERO grey     green  black   orange   red       }

  def render_todo_name(todo)
    title = todo.description
    klasses = "todo #{todo.done? ? 'done' : 'undone' }"
    # Simplified for now, removed on_the_spot_edit
    content_tag( (todo.active ? :b : :s) , todo.name , :title => title , :class => klasses )
  end

  def render_where(todo)
    return unless todo.where.present?
    link_to(
      "📍", 
      "http://maps.google.com?q=#{todo.where}",
      { :title => "#{todo.where}", :target => '_blank' }
    ) 
  end

  def render_todo_second_row(todo)
    ret = []
    ret << content_tag(:span, render_where(todo), :class => :where_small) if todo.where.present?
    
    if todo.overdue?
      ret << content_tag(:span, " (OverDue: #{time_ago_in_words(todo.due)})", :class => "text-red-600 font-bold" ) 
    end
    
    # ret << render_editable_project(todo.project) # Simplified
    
    if todo.still_hidden?
      ret << content_tag(:span, " (hide for: #{time_ago_in_words(todo.hide_until) })", :class => :small_hide_until )
    end

    if todo.progress_status.present? && todo.progress_status > 0
      ret << content_tag(:span, " #{todo.progress_status}%", :class => :progress_status_small)
    end

    if todo.description.present?
       ret << content_tag(:span, " 📝", :title => todo.description, :class => :todo_description_snippet)
    end
    
    # ret << render_tags(todo) # TODO: Port tags rendering

    content_tag(:span, ret.join(" ").html_safe, :class => :second_row )
  end

  def priority_name(num)
    PRIORITIES_NAMES[num]
  end

  def render_priority_icon(priority)
    return if priority == 3 # Normal priority, no icon
    # Using emoji for now instead of images to avoid asset pipeline complexity for this quick port
    icon = case priority
           when 1 then "⬇️"
           when 2 then "🔽"
           when 4 then "🔼"
           when 5 then "⬆️"
           end
    content_tag(:span, icon, :title => "Priority ##{priority}: #{priority_name(priority)}")
  end

  def render_todo_icons(todo)
    icons = []
    icons << render_priority_icon(todo.priority)
    icons << "⚠️" if todo.overdue? # Overdue
    icons << link_to("🔗", todo.url, target: "_blank", title: "Website: #{todo.url}") if todo.url.present?
    icons << link_to("🖼️", todo.photo_url, target: "_blank", title: "Picture") if todo.photo_url.present?
    icons << "❤️" if todo.favorite?
    icons << "🙈" if todo.still_hidden? # Hidden
    
    icons.join(' ').html_safe
  end

  def render_priority(todo)
    priority = todo.priority
    prio_name = PRIORITIES_NAMES[priority]
    color = PRIORITIES_COLORS[priority]
    content_tag(:span , "#{prio_name} (#{priority})", :style => "color:#{color}", :class => "priority_#{priority}")
  end

  def render_duetime(todo)
    return '-' unless todo.due
    time_in_words = time_ago_in_words(todo.due)
    explanation = todo.overdue? ? "#{time_in_words} ago" : "in #{time_in_words}"
    
    color = todo.overdue? ? "red" : "green"
    content_tag( :span, explanation , :style => "color: #{color}")
  end
end

septober_v8/app/views/todos/_form.html.erb
<%= form_with model: todo, local: true do |f| %>
  <% if todo.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :project_id %>
    <%= f.collection_select :project_id, Project.all, :id, :name, { prompt: "Select Project" }, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :due %>
    <%= f.date_field :due %>
  </div>

  <div class="form-group">
    <%= f.label :priority %>
    <%= f.number_field :priority, in: 1..5 %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

septober_v8/app/views/todos/_inline_form.html.erb
<%= turbo_frame_tag todo do %>
  <div class="todo-item" style="border-bottom: 1px solid #e5e7eb; padding: 0.5rem 0;">
    <%= form_with model: todo, local: false, data: { turbo: true } do |f| %>
      <div style="display: flex; gap: 0.5rem; margin-bottom: 0.5rem;">
        <%= f.text_field :name, style: "flex-grow: 1; padding: 0.25rem;", class: "form-control" %>
        <%= f.collection_select :project_id, Project.where(user_id: todo.user_id), :id, :name, {}, { style: "padding: 0.25rem;", class: "form-control" } %>
        <%= f.date_field :due, style: "padding: 0.25rem;" %>
      </div>
      <div style="display: flex; gap: 0.5rem;">
        <%= f.text_area :description, rows: 2, style: "flex-grow: 1; padding: 0.25rem;", class: "form-control", placeholder: "Description" %>
        <div style="display: flex; flex-direction: column; gap: 0.25rem;">
          <%= f.submit "Save", class: "btn btn-primary btn-sm" %>
          <%= link_to "Cancel", todo_path(todo), class: "btn btn-secondary btn-sm" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

septober_v8/app/views/todos/_todo.html.erb
<%= turbo_frame_tag todo do %>
  <div class="todo-item <%= 'done' if todo.done? %>" style="border-bottom: 1px solid #e5e7eb; padding: 0.5rem 0; display: flex; justify-content: space-between; align-items: flex-start;">
    <div style="flex-grow: 1;">
      <div>
        <%= render_todo_icons(todo) %>
        <strong>
          <%# Link to edit page, but Turbo will intercept if we configure the edit view correctly %>
          <%= link_to todo.name, edit_todo_path(todo), data: { turbo_frame: dom_id(todo) } %>
        </strong>
        <span style="font-size: 0.8rem; color: <%= todo.project&.color.presence || '#6b7280' %>; font-weight: bold;">
          <%= todo.project.name if todo.project %>
        </span>
         | <%= render_duetime(todo) %>
      </div>
      <div style="font-size: 0.8rem; color: #6b7280; margin-top: 2px;">
        <%= render_todo_second_row(todo) %>
      </div>
    </div>
    <div style="white-space: nowrap; margin-left: 10px;">
      <% unless todo.done? %>
        <%= link_to "Done", done_todo_path(todo), class: "btn btn-secondary", style: "font-size: 0.8rem;" %>
      <% else %>
        <%= link_to "Undone", undone_todo_path(todo), class: "btn btn-secondary", style: "font-size: 0.8rem; background-color: #9ca3af;" %>
      <% end %>
      <%= link_to "Edit", edit_todo_path(todo), class: "btn", style: "font-size: 0.8rem; background-color: #e5e7eb;", data: { turbo: false } %>
    </div>
  </div>
<% end %>

septober_v8/app/views/todos/edit.html.erb
<div class="card">
  <h2>Edit Todo</h2>
  <%= render "form", todo: @todo %>
  <%= link_to "Back", todos_path, class: "btn" %>
</div>

septober_v8/app/views/todos/index.html.erb
<div class="card">
  <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">
    <h2>Todos</h2>
    <%= form_with url: todos_path, method: :get, local: true, style: "display: flex; gap: 0.5rem;" do |f| %>
      <%= f.text_field :q, value: params[:q], placeholder: "Search todos...", style: "padding: 0.5rem; border: 1px solid #d1d5db; border-radius: 0.375rem;" %>
      <%= f.submit "Search", class: "btn btn-secondary" %>
    <% end %>
    <%= link_to "New Todo", new_todo_path, class: "btn btn-primary" %>
  </div>
  <div style="margin-bottom: 1rem; display: flex; gap: 0.5rem; flex-wrap: wrap;">
    <strong>Filter by Project:</strong>
    <%= link_to "All", todos_path, class: "btn btn-sm", style: "background-color: #e5e7eb; color: #374151;" %>
    <% Project.where(user_id: current_user.id).each do |proj| %>
      <%= link_to proj.name, todos_path(add_project: proj.name), class: "btn btn-sm", style: "background-color: #{proj.color || '#e5e7eb'}; color: white; text-shadow: 0 1px 2px rgba(0,0,0,0.3);" %>
    <% end %>
  </div>

  <div class="todos-list">
    <%= render @todos %>
  </div>
</div>

septober_v8/app/views/todos/new.html.erb
<div class="card">
  <h2>New Todo</h2>
  <%= render "form", todo: @todo %>
  <%= link_to "Back", todos_path, class: "btn" %>
</div>

septober_v8/app/views/todos/show.html.erb
<div class="card">
  <h2><%= @todo.name %></h2>
  <p><strong>Project:</strong> <%= link_to @todo.project.name, @todo.project %></p>
  <p><strong>Due:</strong> <%= @todo.due %></p>
  <p><strong>Priority:</strong> <%= @todo.priority %></p>
  <p><strong>Status:</strong> <%= @todo.active ? "Active" : "Done" %></p>
  
  <% if @todo.description.present? %>
    <p><strong>Description:</strong></p>
    <p><%= @todo.description %></p>
  <% end %>

  <div style="margin-top: 1rem;">
    <% unless @todo.done? %>
      <%= link_to "Done", done_todo_path(@todo), class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "Undone", undone_todo_path(@todo), class: "btn btn-secondary", style: "background-color: #9ca3af;" %>
    <% end %>
    <%= link_to "Edit", edit_todo_path(@todo), class: "btn btn-primary" %>
    <%= link_to "Back", todos_path, class: "btn" %>
  </div>
</div>