config/routes.rb
Septober::Application.routes.draw do

  %w{ index about docs healthz license search statusz varz}.each do |page_action| 
    get "pages/#{page_action}"
  end
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  # Google style endpoints. Helps with k8s too.
  match 'healthz' => 'pages#healthz' 
  match 'statusz' => 'pages#statusz' 
#  match 'varz' => 'pages#varz'
  match 'varz' => 'pages#varz_testuale'

  resources :sessions
  resources :tags
  
  resources :users do
    collection do
      put :update_attribute_on_the_spot
    end
  end
  
  resources :projects do
    collection do
      put :update_attribute_on_the_spot
    end
    resources :todos do   # how do I select only the sub_project stuff?!? 
      #member do
      #  post 'set_public'
      #  post 'set_private'
      #  post 'set_home'
      #  post 'set_no_home'
      #  post 'set_project_description'
      #  get "procrastinate"
      #end
    end
  end
  resources :projects

  #resources :todos
  resources :todos do
    collection do
      # https://github.com/nathanvda/on_the_spot/issues/26 fixed
      put :update_attribute_on_the_spot
    end
    member do
      %w{sleep done undone toggle procrastinate set_priority set_bookmark quick_create_get set_todo_where
        }.each do |todo_peculiar_action|
        get(todo_peculiar_action.to_s )
      end
      %w{quick_create_post}.each do |todo_post_action|
        post todo_post_action  # TODO!
      end
    end
  end
  #resources :todos
  
  namespace :api do
    get "todos/rss"        => "todos#rss"
    resources :todos do
      member do
        put 'done'     #  lynx --dump http://localhost:3000/api/todos/7.xml -auth=guest:guest
        put 'toggle'   # 201905 bug: ActionController::RoutingError (No route matches "/api/todos/65/toggle.json"):
        put 'edit'
        put 'delete'
      end
    end
  end
  
  
  #####################################
  ### RicAddons::Routes
  # TODO move to some magic function.. sth like
  #map.ric_addons
  # include RicAddons
  # RicAddons::ric_addons_set_routes(self)
  # # Routes version 1.0.2
  get "ric_addons"        => "ric_addons#index"
  get "ric_addons/about"
  get "ric_addons/index"
  get "ric_addons/search"
  get "ric_addons/test"
  ### /RicAddons::Routes
  ####################################
  

  resources :projects do
    member do
      get :procrastinate
    end
  end
  
  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #namespace :api do
  ##     # Directs /admin/products/* to Admin::ProductsController
  ##     # (app/controllers/admin/products_controller.rb)
  #  resources :todos
  #end

  namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
    resources :todos
  end


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "todos#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/ric_addons_controller.rb
###
### DONT TOUCH THIS FILE!! It was included automatically. Rather run this again: thor ric_addons:copy_files
### @tags: thor, auto, cool, ric_addons
###
class RicAddonsController < ApplicationController
  layout 'ric_addons_app'
  #render_ric_app
  before_filter :login_required #, :except => [:index, :show]
  
  before_filter :set_subpages
  def set_subpages
    @index_subpages = %w{ about index search test } 
  end
  
  def search
    @query_string = params[:q] || "riccardo"
  end
  
  def index
    #@index_subpages  = %w{ index search tests} 
  end
  
  def about
    
  end
  
  def test
    
  end
  
end

app/helpers/ric_addons_helper.rb
###
### DONT TOUCH THIS FILE!! It was included automatically. Rather run this again: thor ric_addons:copy_files
### @tags: thor, auto, cool, ric_addons
###

# TODO refactor in subdir

module RicAddonsHelper
  
  $anonymnous_default_path ||= "/photos/default.png"
  
  def okno(bool,opts={})
    bool = !!bool #force to boolean :)
    icon_name = bool ? 'done.png' : 'destroy.png'
    opts[:height] ||= 20
    image_tag("ric_addons/icons/#{icon_name}", opts )
  end

  # "aaa.png" =>
  # "/aaa.png" => "RAILS_URL/images/aaa.png" # correct, but adds /images
  # "aaa.png" =>  adds
  def photo_real_url(model, opts={})
    image_dir = opts.fetch :image_dir, '/photos/' # contacts
    my_photo_url = model.photo_url.to_s  # send( opts.fetch(:image_method, :photo_url)) # rescue '' # default_model.png
    my_photo_url = "default.png" if my_photo_url == '' #rescue nil # ||= "default.png"    
    #my_photo_url = $anonymnous_default_path if ( my_photo_url.to_s  == '' )
    my_photo_url =  image_dir + my_photo_url unless my_photo_url.match(/^http[s]?:\/\/|^\//) # i.e. http://www.faceboo.com/myphoto.jpg or HTTPS as well
    my_photo_url = '/images'    + my_photo_url if my_photo_url.match(/^\//)                      # i.e. /icons/... is local
    my_photo_url 
  end

  
  def render_photo_url(model, opts={})
    model_type = model.class.to_s
    height = opts.fetch( :height, 100 )
    url = photo_real_url(model,opts)
    image_tag(url, :height => height , :alt => "Photo for #{model_type}: '#{model}' URL='#{url}'")
  end
  
end

app/views/ric_addons/_footer.html.erb
<%
	ric_websites_ring = {
		#'RAB' => 'http://ricaddressbook.heroku.com/',
		'lo:8080' => 'http://localhost:8080',
		'SeptOberGKE' => 'http://septober.palladius.it',
		'SeptOberGCE' => 'http://septober-gce.palladius.it',
		#'FsDB' => 'http://fsdb.dev.palladius.eu/',
		'RicLife (TODO)' => 'https://riclife.palladius.eu/',
		'Ric Homepage' => 'http://www.palladius.it/',
		'Goldie2020' => 'http://goldie-prod.palladius.it/',
		'Septober on GitHub' => 'https://github.com/palladius/septober'
	}

%><div class='footer' align='center' ><small>
	<p>
		<!-- Line one: appname, version, logo, env -->
		<b class='ric_app' ><%=$APP[:name] rescue "Unknown RicApp" %> v<%=$APP[:version] rescue 'VER_ERR' %></b> - <%=$APP.fetch :copyright, 'All rights reserved (TM)'%>
		[<b><tt><%= Rails.env %></tt></b>]
	<br/>
		<!-- Line two: hostname/IP (for docker) and minor endpoints that only Riccardo cares about -->
	Host: <%= Socket.gethostname %> (<%= Socket.ip_address_list.detect(&:ipv4_private?).ip_address rescue :boh %>) -
	<%= link_to "Page Index", "/pages/index" %> -
	<%= link_to "About", "/pages/about" %> -
	<%#= link_to "Search", "/pages/search" %> -
	<%= link_to "Health", "/healthz" %> -
	<%= link_to "Status", "/statusz" %> -
	<%= link_to "varz", "/varz" %> -
	<%= link_to "License", "/pages/license" %> -

		<!-- Line three: Carlessian Ring (very 90s) -->
	<br/>
		Ring: [
		<%= ric_websites_ring.map{|appname,url| link_to(appname,url)}.join(' :: ').html_safe %>
		]
	<%#= RicPlugin.ric_websites_ring rescue "Problems to include ric_websites_ring" %>
	</p>
	</small>
	</div>

<% if Rails.env == 'development' && $debug_info != {} %>
	<hr/>
	<h2>Development Debug Info from <tt>$debug_info</tt></h2>

	<table border='0' >
	<% $debug_info.each do |k,v| %>
		<tr>
			<td>
				<b><%= k %>:</b>
			<td>
				<tt><%= v.inspect %></tt>
	<% end %>
	</table>
<% end %>

<div id="logo">
	<a href="http://www.palladius.it/" >
		<%= image_tag('ric_addons/icons/powered_by_palladius.png', :alt => 'Riccardo Website' ) %>
	</a>
<div>

app/views/ric_addons/_header.html.erb
<%
  $debug_info[:sessions] = session
  @base_models = $APP.fetch :base_models , %w{ ric_addons#how_to_add_base_models }
%>
<table border='0' width='100%' class='header_table' 
	BACKGROUND="/images/logo-banner.png"
	style="opacity:0.7;filter:alpha(opacity=50);background-repeat:no-repeat;"
>
	<tr>
		<td align='center' width='80%' >
			<%= link_to( '<b>Home</b>'.html_safe ,"/") %> 
			<% @base_models.each do |model| %> 
				<%= link_to(model,"/#{model.gsub(/#/,'/')}") %>
			<% end %> 
		</td>
		<td align='right' >
			<%= render :partial => 'ric_addons/minimal_search_form' %>
		</td>
	</tr>
	<tr>
		<td colspan=''>
			<h2><a href='/'><%=$APP_NAME%></a> </h2>
			"<i><%= $APP_HEADLINE %></i>"
		</td>
		<td valign='top' >
			<%= render :partial => 'ric_addons/nifty_login' %>
		</td>
	</tr>
</table>

app/views/ric_addons/_minimal_search_form.erb
<%= form_tag( '/ric_addons/search', :method => 'get' ) do %>
  <%= text_field_tag 'q', "Search RicLife", :onfocus => "document.getElementById('q').value = ''" %>
  <script type="text/javascript">
    document.getElementById('q').focus();
  </script>
<% end %>

app/views/ric_addons/_nifty_login.html.erb
<%
	# Copied by RBates nifty authentication => generated into lib/controller_authentication.rb
	# and extracted here as a first test
	
	# BUG found: link_to with no space!
%>
	<% if logged_in? %>
	  VVelcome <b><%= link_to(current_user.username.capitalize, edit_current_user_path, :title => "RicPlugin: User number ##{current_user.id}", :class => 'user') %></b>.
	  <%= link_to "Log out", logout_path %>
	<% else %>
	  <%= link_to "Sign up", signup_path %> or
	  <%= link_to "log in", login_path %>
	<% end %>

app/views/ric_addons/index.html.erb
<% 
	#@index_subpages  = %w{ index search tests} 
%>
<% title "RicAddons :: Index" %>

<h2>Pages</h2>
	[ <% @index_subpages.each do |subpage| %>
  <%= link_to(subpage, "/ric_addons/#{subpage}") %>
	<% end %> ]
Here you can find some info..

<h1>Models</h1>

TODO

<h1>Users</h1>

<div class='users_list'>
	Users: <%= User.all.map{|u| render_user(u) }.join(', ').html_safe %>
</div>

app/views/ric_addons/search.html.erb
<%
 #@searchable_models = ApplicationHelper::HEADER_MODELS rescue [ Project,Todo,User ] 
 @searchable_models = [ Project,Todo ] 
%>
<% title "RicAddon::Search for #{@query_string}" %>

 <%#= link_to "Tags for #{@query_string }", "/tags/#{@query_string }" %>

<% @searchable_models.each{ |model|
	begin
%>
<% 
  #@entries = model.search(current_user, @query_string)	
  @entries = model.search_for_user(current_user, @query_string)	
  if @entries.size > 0
%>
	<p>
		<b><%= link_to( pluralize( @entries.size, model.to_s) , "/#{model.to_s.pluralize.downcase}/" )%> with  '<%= @query_string %>':</b>
	<% @entries.each { |entry|	%>
		<%= link_to( (entry.to_html.html_safe rescue entry.to_s), entry) %>,
	<%	} %>
	.</p>
<% else %>
	<p>Sorry, nothing found for <%=model %>.
		<!-- (Query was: <tt><%=model.search_conditions(@query_string).inspect%></tt>). -->
<% end
	rescue Exception => e
	 %>
	 <h5>Exception for <%= model %>: <span class='debug'><%=  $! %></span> </h5>
	<%
end


} %>

app/views/ric_addons/test.html.erb
<%
	vars_to_inspect = {
		:routes => @index_subpages,
		:VERSION => :TODO
		
	}
	

%>
<% title :Test %>

<pre><%= vars_to_inspect.inspect %></pre>