config/routes.rb
Septober::Application.routes.draw do

  %w{ index about docs healthz license search statusz varz}.each do |page_action| 
    get "pages/#{page_action}"
  end
  
  match 'user/edit' => 'users#edit', :as => :edit_current_user
  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  # Google style endpoints. Helps with k8s too.
  match 'healthz' => 'pages#healthz' 
  match 'statusz' => 'pages#statusz' 
#  match 'varz' => 'pages#varz'
  match 'varz' => 'pages#varz_testuale'

  resources :sessions
  resources :tags
  
  resources :users do
    collection do
      put :update_attribute_on_the_spot
    end
  end
  
  resources :projects do
    collection do
      put :update_attribute_on_the_spot
    end
    resources :todos do   # how do I select only the sub_project stuff?!? 
      #member do
      #  post 'set_public'
      #  post 'set_private'
      #  post 'set_home'
      #  post 'set_no_home'
      #  post 'set_project_description'
      #  get "procrastinate"
      #end
    end
  end
  resources :projects

  #resources :todos
  resources :todos do
    collection do
      # https://github.com/nathanvda/on_the_spot/issues/26 fixed
      put :update_attribute_on_the_spot
    end
    member do
      %w{sleep done undone toggle procrastinate set_priority set_bookmark quick_create_get set_todo_where
        }.each do |todo_peculiar_action|
        get(todo_peculiar_action.to_s )
      end
      %w{quick_create_post}.each do |todo_post_action|
        post todo_post_action  # TODO!
      end
    end
  end
  #resources :todos
  
  namespace :api do
    get "todos/rss"        => "todos#rss"
    resources :todos do
      member do
        put 'done'     #  lynx --dump http://localhost:3000/api/todos/7.xml -auth=guest:guest
        put 'toggle'   # 201905 bug: ActionController::RoutingError (No route matches "/api/todos/65/toggle.json"):
        put 'edit'
        put 'delete'
      end
    end
  end
  
  
  #####################################
  ### RicAddons::Routes
  # TODO move to some magic function.. sth like
  #map.ric_addons
  # include RicAddons
  # RicAddons::ric_addons_set_routes(self)
  # # Routes version 1.0.2
  get "ric_addons"        => "ric_addons#index"
  get "ric_addons/about"
  get "ric_addons/index"
  get "ric_addons/search"
  get "ric_addons/test"
  ### /RicAddons::Routes
  ####################################
  

  resources :projects do
    member do
      get :procrastinate
    end
  end
  
  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #namespace :api do
  ##     # Directs /admin/products/* to Admin::ProductsController
  ##     # (app/controllers/admin/products_controller.rb)
  #  resources :todos
  #end

  namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
    resources :todos
  end


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "todos#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/api/todos_controller.rb
class Api::TodosController < ApplicationController
  before_filter :authorize_episode95
  #helper :riccardo
  
  def index
    filter_conditions = { :user_id => current_api_user.id  } 
    #  Project: , :home_visible => true
    filter_conditions[:project_id] = Project.find_by_name_and_user_id(params[:add_project], current_api_user.id).id if params[:add_project]
    filter_conditions[:projects] = { :home_visible => true } unless params[:add_project] # in which case i show everything
    @todos = Todo.find :all, 
      :joins => :project,
      :conditions => filter_conditions, 
      :order => 'active DESC, priority DESC, updated_at DESC',
      :limit => 20
    respond_to do |format|
      format.html 
      format.xml  { render_todos_xml_or_json :xml,  @todos } # :due_explaination
      format.json { render_todos_xml_or_json :json, @todos }
    end
  end

  def show
    @todo = Todo.find_securely(current_api_user,params[:id]) rescue nil
    respond_to do |format|
      format.html 
      format.xml  { render_todos_xml_or_json :xml,   @todo } # :include => [:project] , :methods => [:due_explaination] }
      format.json { render_todos_xml_or_json :json , @todo }
    end
  end

  def new
    puts("\n\nNEW params vale: #{params}\n\n")
    pgray "[RiccDEBUGNEW] API::TodoController.create() - param[:todo]=#{params[:todo]}"
    @todo = Todo.new(params[:todo])
    puts("BUG This seems to be broken :/")
    pred("Big Bug dig dug drank drunk")
    # errore credo sia questo: WARNING: Can't mass-assign protected attributes: action, controller, format
    # foprse manca params nel costruittore? forse manca post_params?
  end

  def create
    #pgreen "DEBUG API::TodoController.create()"
    # 20190512 For some reasons, params comes virgin, wihtout [:todo] so I need to push one level.
    params[:todo] = params
    pgray "[RiccDEBUG] API::TodoController.create() - param[:todo]=#{params[:todo]}"

    params[:todo][:user_id] = current_api_user.id
    @todo = Todo.new(params[:todo]) # both HTML and XML :)
    @todo.user_id = current_api_user.id
    @todo.apply_todo_regex_magic() rescue pred("Couldnt apply regex for TODO: #{ @todo }. Error: ''#{ $! }''")
    ret = @todo.save
    respond_to do |format|
      format.xml { 
        if ret
          pred "[RiccDEBUG XML] API::TodoController.create() - ALL GOOD WITH CREATION: param[:todo]=#{params[:todo]}"
          render(:xml => @todo.to_xml, :status => "201 Created yay", :message => "Yay API TOdo created id=TODO") 
        else
          pred "[RiccDEBUG XML] API::TodoController.create() - SOMETHING WRONG WITH CREATION: param[:todo]=#{params[:todo]}"
          render(:xml => @todo.to_xml , :status => :unprocessable_entity, :message => "ERROR API TOdo NOT created id=TODO")
        end
      }
      format.json  { 
        if ret
          pred "[RiccDEBUG JSON] API::TodoController.create() - ALL GOOD WITH CREATION: param[:todo]=#{params[:todo]}"
          render(:json => @todo.to_json, :status => "201 Created yay", :message => "Yay API TOdo created id=TODO") 
        else
          pred "[RiccDEBUG JSON] API::TodoController.create() - SOMETHING WRONG WITH CREATION: param[:todo]=#{params[:todo]}. ret=#{ret}. Errors: #{ @todo.errors}"
          render(:json => @todo.to_json, 
            #:status => "572 JSON Couldnt save it sorry", 
            :status => :unprocessable_entity,
            :message => "ERROR API TOdo NOT created id=TODO. Forse duplicato", 
            :error => "TODO Ho fallito perche: #{ @todo.errors.full_messages }",
            :errors => "TODO Ho fallito perche: #{ @todo.errors.full_messages }",
            #:code => "code",
          )
        end
      }
      format.js # do nothing
    end #/respond_to
    ret_enforced = @todo.save
    pgray( "[RiccDEBUG] API::TodoController.create() - ret[todo save]=#{ret_enforced}")
    return ret_enforced
  end #/create

  def edit
    @todo = Todo.find_securely(current_api_user,params[:id])
  end
  
  def rss
    #@todos = Todo.find(:all, :order => "id DESC", :limit => 20)
    @user  = current_api_user
    @todos = Todo.active.find_securely(current_api_user, :all, :order => "id DESC", :limit => 20)
    render :layout => false
    response.headers["Content-Type"] = "application/xml; charset=utf-8"
  end

  def update
    pyellow "DEBUG API::TodoController.update()"
    # params[:todo][:user_id] = current_api_user.id
    #raise "why should u call update from API? TODO"
    @todo = Todo.find(params[:id])
    @todo.user_id = current_api_user.id
    @todo.apply_todo_regex_magic()
    
    respond_to do |format|
      format.xml { 
        if @todo.save
          render(:xml => @todo.to_xml,  :status => "201 Created yay") 
        else
          render(:xml => @todo.to_xml , :status => "568 Couldnt save it sorry", :message => "XML Update Err: TODO")
        end
      }
    end
  end
  
  def toggle; _update_active(:toggled) ; end 
  def done;   _update_active(:deactivated,false) ; end
  def undone; _update_active(:reactivated,true) ; end
  def set_priority
    _update_field(:priority,params[:new_priority])
  end
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    flash[:notice] = "Successfully destroyed todo."
    #redirect_to todos_url
  end
  def edit
    #@todo = Todo.find(params[:id])
    # 2020 not sure if this works
    update
  end
  def delete
    _update_active("delete")
  end
  
private
  def project_find_for_cli(params={})
    Project.find_by_name('personal') || Project.first
  end
  def _update_active(participle,new_active=nil)
    # nil = toggle
    new_active ||= false # should be the REVERSE... TODO!
    # copy the data from edit
    #@todo = Todo.find(params[:id])
    @todo = Todo.find_securely(current_api_user, params[:id])
    if @todo.update_attributes( :active => new_active )
      flash[:notice] = "Successfully '#{participle}'d todo ##{params[:id]}"
      #redirect_to todos_url
    else
      render :action => 'edit'
    end
  end
  
  
  # episode 95 for Remote app with authentication
  # Episode 82 for multiple auth...
  def authorize_episode95
   # user = User.authenticate(params[:login], params[:password])
   # if user
   #   session[:user_id] = user.id
   #   flash[:notice] = "Logged in successfully."
    user = nil
    return authenticate_or_request_with_http_basic do |username, password|
      #username == "guest" && password == "guest"
      #user = 
      user = User.authenticate(username, password )
      if user
        session[:api_user_id] = user.id 
      end
      puts "\n\nDEBUG (API authorize_episode95): user='#{user.id rescue "NoId:"}'\n\n"
      return user
    end
    #if user
    #  session[:user_id] = user.id 
    #end
    # return user || login_required # passing to Ryan Bates thing..
  end
  
  
=begin
  # to DRY the methods for TODOS index and TODO show..
  protocol: :xml or :json
  Possible options:
  - :only=>['id','title'] (either on master model or submodels) to restrict explicitally
  - :include for DB relationships
  - :methods for custom model methods
  - for all the rest, there is mastercard. ehm, no, there is explicit XML builder in the view... or here :)

  Resources:
  - http://stackoverflow.com/questions/4363870/rails-json-rendering-ambiguous-table-column-names
=end
    def render_todos_xml_or_json(protocol, object_s) # object(s)
      render protocol => object_s,
        :include => {
          :project=> {:only => [:name, :color ] }
        },
        :methods => [:due_explaination, :tag_list] ,
        :except => [:sys_notes]
    end  

end #/TodosController

app/helpers/todos_helper.rb
module TodosHelper
  
                #  Priorities  1        2      3       4        5
  $priorities_names = %w{ ZERO very_low low    normal  high     very_high }
  $priorities_colors= %w{ ZERO grey     green  black   orange   red       }
  
  def render_todo_name(todo, opts={} )
    title = [
      todo.description
      ].join("\n")
    klasses = "todo #{todo.done? ? 'done' : 'undone' }"
    coloured_todo = render_within_project(todo.project,on_the_spot_edit(todo, :name, :tooltip => todo.description ) ) rescue "TodoErr('#{$!}')"
    ret = content_tag( (todo.active ? :b : :s) , coloured_todo , :title => title , :alt => :alt , :class => klasses ) # , :id => "todo_#{todo.id}")
    return ret
  end
  
  def render_where(todo)
    link_to(
      icon('map') , 
      "http://maps.google.com?q=#{todo.where}",
      {
      :title => "#{todo.where}"
      #:method => :post,
      #:confirm => "Are you sure to go to google map?!?",
      
      },
      :popup => true ,
      :target => '_blank' 
    ) 
    #iconed_link_to('GugolMap', todo.where, "http://maps.google.com/q?#{todo.where}") 
    # , 
  end
  
  # This renders the second line after a todo name in todo Index
  def render_todo_second_row(todo,opts={})
    ret = ''
      # short things
    ret += content_tag(:span, render_where(todo), :class => :where_small) if todo.where?
    ret += content_tag(:span, " (OverDue: #{time_ago_in_words(Time.now - todo.due)  rescue todo.due})", :class => :small_overdue ) if todo.overdue?
    ret += render_editable_project(todo.project)
    ret += content_tag(:span, " (hide for: #{time_ago_in_words(todo.hide_until) })", :class => :small_hide_until ) if todo.still_hidden?
    ret += content_tag(:span, " #{on_the_spot_edit(todo, :progress_status)}%".html_safe, :class => :progress_status_small) if todo.progress_status?
      # long
    #ret += content_tag(:span, ' ' + truncate_words(todo.description), :class => :todo_description_snippet)
    ret += content_tag(:span, (' ' + on_the_spot_edit(todo, :description, :tooltip => 'Edit Description')).html_safe, :class => :todo_description_snippet) 
    ret += render_tags(todo)
    
    #ret.html_safe
    return content_tag(:span, ret.html_safe, :class => :second_row )
  end
  
  ### AAHAHAAHH super! TODO put in ric_addons
  def render_icon_grayable(icon_path, gray, opts={})
    image_tag("#{icon_path}#{gray ? '-grey' : ''}.png", opts)
  end
  
  def render_icon_favorite(todo,opts={})
    render_icon_grayable('icons/todo/favorite', ! todo.favorite, opts.merge(:title => "Favorite is #{todo.favorite}") )
  end
  
  def priority_name(num)
    $priorities_names[num]
  end

  def render_priority_icon(priority,opts={})
    image_tag("icons/priorities/#{priority}.png" , :title => "Priority ##{priority}: #{priority_name(priority)}", :height => 12) unless priority == 3
  end
  
  def eventual_link_priority(todo,raise_or_lower) 
    icon1 = raise_or_lower ? 5 : 1
    icon2 = raise_or_lower ? 4 : 2
    new_priority = raise_or_lower ? todo.priority+1 : todo.priority-1
    exception_priority = raise_or_lower ? 5 : 1
    action = raise_or_lower ? 'raise' : 'lower'
    updown_icon = raise_or_lower ? 'up10x8' : 'down10x8'
    icon_gray = 'white-10x8.png'
    # LOWER/RAISE link
    return link_to( 
      image_tag("icons/priorities/#{updown_icon}-grey.png",
        :mouseover => "icons/priorities/#{updown_icon}.png"  ,
        :height => 8,
        :width => 10
      ),
      "/todos/#{todo.id}/set_priority?new_priority=#{new_priority}", :title => "#{action} priority from #{todo.priority} to #{new_priority}" 
    ) unless todo.priority==exception_priority
    # return gray and NOT linked
    return image_tag("icons/priorities/#{icon_gray}", :width => 10, :height => 8, :title => "Can't #{action} further..")
  end
  
  
  def render_todo_action_icons(todo,opts={})
    cell_height = opts.fetch :cell_height, 40
    border = opts.fetch :border, 0
    icons = []
    ## Priority raise, rtable of 2..
    icons << "<table border='0' ><tr><td width='11' height='16' >" +
        eventual_link_priority(todo, true) +
      #{}"<tr><td >" +
        eventual_link_priority(todo, false)+
      "</table>"
      
    ## Mark as done..
    icons << link_to( 
      image_tag("icons/todo/V-grey.png", :mouseover => "icons/todo/V.png", :height => cell_height) ,
      "/todos/#{todo.id}/done", :title => t(:mark_as_done)
    ) unless todo.done?
    # Formatting the return as a table on its own..
    return ( "<table border=\"#{border}\" ><tr><td height=\"#{cell_height}\" >" + 
      icons.join("</td><td height=\"#{cell_height}\" >") + 
      '</table'
    ).html_safe
  end
  
  def render_todo_icons(todo,opts={})
    icons = []
    height = opts.fetch :height, 12
    icons << render_priority_icon(todo.priority)
    icons << image_tag("icons/todo/overdue.png", :title => 'Overdue!', :height => 12) if todo.overdue?
    icons << link_to(image_tag("ric_addons/icons/website.png", :title => "Website: #{todo.url}", :height => height), todo.url) if todo.url?
    icons << link_to(image_tag("ric_addons/icons/photo_url.png", :title => "Picture: #{todo.photo_url}", :height => height), todo.photo_url) if todo.photo_url?
    icons << image_tag("icons/todo/favorite.png", :title => "You must like this", :height => height) if todo.favorite?
    icons << image_tag("icons/todo/hidden.png", :title => "Hidden Until: #{todo.hide_until}", :height => height) if todo.still_hidden?
    
    # Add more icons here...
    icons.join(' ').html_safe
  end
  
  def render_priority(todo)
    priority = todo.priority
    prio_name = $priorities_names[priority]
    content_tag(:span , "#{prio_name} (#{priority})", :style => "color:"+$priorities_colors[priority], :class => "priority_#{priority}")
  end
  
  def render_todo_hide_until(todo)
    ret = todo.hide_until.to_s || '-' # Time.now
    ret += content_tag(:i, " (#{t :in_the_future_particle} #{time_ago_in_words( todo.hide_until )})") if todo.hide_until
    ret.html_safe
  end
  
  def render_duetime(todo,opts={})
    return '-' unless todo.due
    # TODO: due could NOT exist!
    style_class = "due_explain_#{todo.due_explaination}"
    time_in_words = time_ago_in_words(todo.due.to_time)
    explaination = todo.overdue? ? "#{time_in_words} ago" : "in #{time_in_words}"
    content_tag( :span, explaination , :class => style_class)
  end


end

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <%= f.error_messages %>
    (by <b class='user' ><%= @todo.user rescue '?!?' %></b>)
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :where %><br />
    <%= f.text_field :where %>
  </p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :photo_url %><br />
    <%= f.text_field :photo_url %>
  </p>
  <p>
    <%= f.label      :tags %><br />
    <%= f.text_field :tags %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p>
    <%= f.label :favorite %><br />
    <%= f.check_box :favorite %>
  </p>
  <p>
    <%= f.label :priority %><br />
    <% [1,2,3,4,5].each do |prio| %>
      <%= render_priority_icon(prio) %>
      <%= f.radio_button("priority", prio ) %>
        <%= priority_name(prio) %> <br/>
    <% end %>
    <%#= f.range_field :priority %>
  </p>
  <p>
    <%= f.label :due %><br />
    <%= f.date_select :due %>
  </p>
  <p>	
	<input type="range" min="0" max="100" id="todo_progress_status" name="todo[progress_status]" value="<%=@todo.progress_status %>"  >
	<%= f.label( :progress_status ) %> (percentage. Works on Safari and Chrome!)
  </p>
  <p>
    <%= f.label :hide_until %><br />
    <%= f.datetime_select :hide_until %>
  </p>
  <p>
    <%= f.label :depends_on %> (father)<br />
    <%#= f.text_field :depends_on_id %>
    <%= collection_select("todo", :depends_on_id , Todo.find_all_by_user_id_and_active(current_user.id,true, :order => :name) , :id, :name , :include_blank => true ) %>
  </p>
  <p>
    <%= f.label :project_id %><br />
    <%= f.collection_select(:project_id , Project.find_all_by_user_id(current_user.id, :order => "id") , :id, :name_and_activity , :include_blank => false ) %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/todos/_oneline_create.html.erb
<%
  @quick_todo = Todo.new
	# description = 'Welcome to quick add. Try the following titles:
	# 	"Improtant ticket!!"
	# 	"--low pri ticket"
	# 	"call mum by tomorrow"
	# 	...
	# '
%>
<div class='todo_oneline' >
<%= form_for @quick_todo do |f| %>
  <%= f.error_messages %>
  <p><%#= t(:quick_create) %>
    <%= f.text_field :name %>
    Prio: <%= f.select :priority, 1..5, :default => 3 %>
    Proj: <%= f.collection_select(:project_id , Project.find_all_by_user_id_and_active(current_user.id,true, :order => "id") , :id, :name , :include_blank => false ) rescue "((ProjErr: #{$!}))" %>
<!--
    Due: <%#= f.date_select(:due) rescue "((DueErr: #{$!}))" %>
-->
<%= f.submit 'Add Todo' %></p>
<% end if logged_in? %>
</div>

app/views/todos/_show.html.erb
	<div class='photo_right' align_removem='right' >
    <%= link_to( 
      image_tag("icons/todo/V-grey.png", :mouseover => "icons/todo/V.png", :height => 50) ,
      "/todos/#{@todo.id}/done", :title => t(:mark_as_done)
    ) unless @todo.done? %>
		<table border='0'><tr><td>
		<%= render_photo_url(@todo, :height => 200 ) if @todo.photo_url? %>
		</table>
	</div>
	<h1><%= render_todo_name(@todo) %></h1>
	<p>
	  <%= iconed_link_to "Edit", edit_todo_path(@todo) %> |
	  <%= iconed_link_to "Destroy", @todo, :confirm => 'Are you sure?', :method => :delete %> |
	  <%= iconed_link_to "View All", todos_path %>
	</p>
	<p>
	  <strong>Due:</strong>
	  <%= @todo.due %>
	</p>
	<p>
	  <strong>Tags:</strong>
	  <%= render_tags(@todo) %>
	</p>
	<p>
	  <strong>favorite:</strong>
	  <%= render_icon_favorite( @todo ) %>
	</p>
	<p>
	  <strong>Progress Status:</strong>
	  <%= @todo.progress_status %>%
	</p>
	<p>
	  <strong>Hide Until:</strong>
	  <%= render_todo_hide_until(@todo) %>
	</p>
	<p>
	  <strong>Priority:</strong>
	  <%= render_priority(@todo) %>
	</p>
	<p>
	  <strong>Project:</strong>
	  <%= link_to( render_project(@todo.project), @todo.project ) %>
	  (<%= iconed_link_to "Edit", edit_project_path(@project) %>)
	</p>
	<p>
	  <strong>Where:</strong>
	  <%= (@todo.where) rescue "Err('#{$!}')"%>
	</p>
	<p>
	  <strong>URL:</strong>
	  <%= @todo.url rescue "ErrURL('#{$!}')"%>
	</p>
	<p>
	  <strong>Depends on (parent):</strong>
	  <%= link_to( render_todo_name(@todo.todo), @todo.todo ) if @todo.todo %>
	  <%#= @todo.depends_on_id %>
	</p>
	<p>
	  <strong>Depended upon (children):</strong>
	  <% Todo.find_all_by_user_id_and_depends_on_id(current_user.id, @todo.id).each do |sub_todo|%>
	  	<%= link_to( render_todo_name(sub_todo),sub_todo ) %>
	  <% end %>
	</p>
	<hr/>
	<p>
		<pre>
	  		<%= @todo.description %>
		</pre>
	</p>
	<hr/>
	<p class='todo-system-notes'>
		<tt>
	  		<%= @todo.sys_notes %>
		</tt>
	</p>

app/views/todos/_tr_line.html.erb
<% 
	css_tr_classes = ['todo_line']
 	css_tr_classes << "done_#{todo.done?}" unless session['todo_filters'].include?('inactive')
	css_tr_classes << "overdue_#{todo.due_explaination}" 
	css_tr_classes << "stillhidden_#{todo.still_hidden?}" unless session['todo_filters'].include?('show_hidden')
%>
<tr class="<%= css_tr_classes.join(' ') %>" >
  <td width='80' >
    <%= render_todo_action_icons(todo) %>
  </td>
	<td>
	  <%= render_todo_name(todo) %>
	  <br/>
      <%= render_todo_icons(todo) %>
      <%= render_todo_second_row(todo) %>
  </td>
  <td class='todo_due_column due_column_<%todo.due_explaination%>' align='right' >
    <%= render_duetime(todo) %>
	<%= link_to(
			  image_tag("icons/todo/procrastinate-grey.png", :mouseover => "icons/todo/procrastinate.png", :height => 25), 
			  "/todos/#{todo.id}/procrastinate" ,
			  :title => "Procrastinate a week or so.."
			)%>
		<%= link_to(
					image_tag("icons/todo/sleep.png",:mouseover => "icons/todo/sleep-sheep.png"  ,:height => 25),
					"/todos/#{todo.id}/sleep?hide_until_days=5" ,
					:title => "Hide Until next week or so.."
				) 
		%>
  </td>
  <td align='right' ><small>
      <%= iconed_link_to "Undone", "/todos/#{todo.id}/undone", :short => true rescue "ToggleRoutigErr (#{$!})" if todo.done?  %>
      <%= iconed_link_to "Show", todo, :short => true  %>
      <%= iconed_link_to "Edit", edit_todo_path(todo), :short => true  %>
      <%= iconed_link_to "Destroy", todo, :confirm => 'Are you sure you want to delete this? You know you can mark it as done as well? ARE YOU SURE?', :method => :delete, :title => 'Are you sure u want to delete this ticket and not rather mark it as done?!?', :short => true %>

    </small>
    <div id='todo-<%=todo.id%>-detail' ></div>
  </td>
</tr>

app/views/todos/edit.html.erb
<% title "Edit Todo" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @todo %> |
  <%= link_to "View All", todos_path %>
</p>

app/views/todos/index.html.erb
<table width='100%' border="0" >
  <tr width='100%' >
    <th>Actions</th>
    <th>Todos</th>
    <th>Due</th>
    <th>Options</th>
  </tr>
  <% for todo in @todos %>
	<%= render :partial => "todos/tr_line", :locals => { :todo => todo , :parity => :odd_even_todo } %>
  <% end %>
</table>

<p><%=t :New %><%= iconed_link_to :Todo, new_todo_path(todo) %></p>

app/views/todos/new.html.erb
<% title "New Todo" %>
<%= render 'form' %>

<p><%= link_to "Back to List", todos_path %></p>

app/views/todos/show.html.erb
<% if @todo %>
	<%= render :partial => "todos/show"  %>
<% else %>
	<div class='error' >
	  <%= image_tag('ric_addons/pics/ricarrabbiato.jpg')%>
  	<%=t(:todo_not_found)%>: Maybe the ticket #<% @id %> was not found, or is not visible by you!
	</div>
<% end %>

app/views/todos/show.text.erb
<%= '-' * (@todo.name.length) %>
<%= @todo.to_s %>
<%= '-' * (@todo.name.length) %>

<%= @todo.description %>

--
Priority: <%= @todo.priority %>
Project: <%= @todo.project%>
Due: <%= @todo.due %><%=@todo.overdue? ? ' (overdue)' : '' %>
URL: <%= url_for @todo %>